// Comments
export const GET_COMMENT_COLLECTION = 'GET_COMMENT_COLLECTION'
export const GET_MORE_COMMENTS = 'GET_MORE_COMMENTS'
export const DELETE_REAL_TIME_COMMENT_COLLECTION = 'DELETE_REAL_TIME_COMMENT_COLLECTION'
export const UPDATE_REAL_TIME_COMMENT_COLLECTION = 'UPDATE_REAL_TIME_COMMENT_COLLECTION'
export const DELETE_MORE_COMMENTS = 'DELETE_MORE_COMMENTS '
export const UPDATE_MORE_COMMENTS = 'UPDATE_MORE_COMMENTS '
export const LAODING_COMMENTS = 'LAODING_COMMENTS'
export const ERROR_COMMENTS = 'ERROR_COMMENTS'
// User Profile
export const DATA_USER_PROFILE = 'DATA_USER_PROFILE'
export const IMAGE_AVATAR_USER = 'IMAGE_AVATAR_USER'